#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteleriaWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PasteleriaDB")]
	public partial class PasteleriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertIngrediente(Ingrediente instance);
    partial void UpdateIngrediente(Ingrediente instance);
    partial void DeleteIngrediente(Ingrediente instance);
    partial void InsertIngredientePastel(IngredientePastel instance);
    partial void UpdateIngredientePastel(IngredientePastel instance);
    partial void DeleteIngredientePastel(IngredientePastel instance);
    partial void InsertPastel(Pastel instance);
    partial void UpdatePastel(Pastel instance);
    partial void DeletePastel(Pastel instance);
    #endregion
		
		public PasteleriaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PasteleriaDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PasteleriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PasteleriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PasteleriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PasteleriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ingrediente> Ingrediente
		{
			get
			{
				return this.GetTable<Ingrediente>();
			}
		}
		
		public System.Data.Linq.Table<IngredientePastel> IngredientePastel
		{
			get
			{
				return this.GetTable<IngredientePastel>();
			}
		}
		
		public System.Data.Linq.Table<Pastel> Pastel
		{
			get
			{
				return this.GetTable<Pastel>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ingrediente")]
	public partial class Ingrediente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idIngrediente;
		
		private string _nombreIngrediente;
		
		private int _cantidadExistente;
		
		private decimal _precioIngrediente;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<IngredientePastel> _IngredientePastel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidIngredienteChanging(int value);
    partial void OnidIngredienteChanged();
    partial void OnnombreIngredienteChanging(string value);
    partial void OnnombreIngredienteChanged();
    partial void OncantidadExistenteChanging(int value);
    partial void OncantidadExistenteChanged();
    partial void OnprecioIngredienteChanging(decimal value);
    partial void OnprecioIngredienteChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Ingrediente()
		{
			this._IngredientePastel = new EntitySet<IngredientePastel>(new Action<IngredientePastel>(this.attach_IngredientePastel), new Action<IngredientePastel>(this.detach_IngredientePastel));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idIngrediente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idIngrediente
		{
			get
			{
				return this._idIngrediente;
			}
			set
			{
				if ((this._idIngrediente != value))
				{
					this.OnidIngredienteChanging(value);
					this.SendPropertyChanging();
					this._idIngrediente = value;
					this.SendPropertyChanged("idIngrediente");
					this.OnidIngredienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreIngrediente", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombreIngrediente
		{
			get
			{
				return this._nombreIngrediente;
			}
			set
			{
				if ((this._nombreIngrediente != value))
				{
					this.OnnombreIngredienteChanging(value);
					this.SendPropertyChanging();
					this._nombreIngrediente = value;
					this.SendPropertyChanged("nombreIngrediente");
					this.OnnombreIngredienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidadExistente", DbType="Int NOT NULL")]
		public int cantidadExistente
		{
			get
			{
				return this._cantidadExistente;
			}
			set
			{
				if ((this._cantidadExistente != value))
				{
					this.OncantidadExistenteChanging(value);
					this.SendPropertyChanging();
					this._cantidadExistente = value;
					this.SendPropertyChanged("cantidadExistente");
					this.OncantidadExistenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioIngrediente", DbType="Decimal(8,2) NOT NULL")]
		public decimal precioIngrediente
		{
			get
			{
				return this._precioIngrediente;
			}
			set
			{
				if ((this._precioIngrediente != value))
				{
					this.OnprecioIngredienteChanging(value);
					this.SendPropertyChanging();
					this._precioIngrediente = value;
					this.SendPropertyChanged("precioIngrediente");
					this.OnprecioIngredienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Bit")]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingrediente_IngredientePastel", Storage="_IngredientePastel", ThisKey="idIngrediente", OtherKey="idIngrediente")]
		public EntitySet<IngredientePastel> IngredientePastel
		{
			get
			{
				return this._IngredientePastel;
			}
			set
			{
				this._IngredientePastel.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IngredientePastel(IngredientePastel entity)
		{
			this.SendPropertyChanging();
			entity.Ingrediente = this;
		}
		
		private void detach_IngredientePastel(IngredientePastel entity)
		{
			this.SendPropertyChanging();
			entity.Ingrediente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IngredientePastel")]
	public partial class IngredientePastel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idIngredientePastel;
		
		private int _idPastel;
		
		private int _idIngrediente;
		
		private int _cantidad;
		
		private decimal _precioIngrediente;
		
		private EntityRef<Ingrediente> _Ingrediente;
		
		private EntityRef<Pastel> _Pastel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidIngredientePastelChanging(int value);
    partial void OnidIngredientePastelChanged();
    partial void OnidPastelChanging(int value);
    partial void OnidPastelChanged();
    partial void OnidIngredienteChanging(int value);
    partial void OnidIngredienteChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    partial void OnprecioIngredienteChanging(decimal value);
    partial void OnprecioIngredienteChanged();
    #endregion
		
		public IngredientePastel()
		{
			this._Ingrediente = default(EntityRef<Ingrediente>);
			this._Pastel = default(EntityRef<Pastel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idIngredientePastel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idIngredientePastel
		{
			get
			{
				return this._idIngredientePastel;
			}
			set
			{
				if ((this._idIngredientePastel != value))
				{
					this.OnidIngredientePastelChanging(value);
					this.SendPropertyChanging();
					this._idIngredientePastel = value;
					this.SendPropertyChanged("idIngredientePastel");
					this.OnidIngredientePastelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPastel", DbType="Int NOT NULL")]
		public int idPastel
		{
			get
			{
				return this._idPastel;
			}
			set
			{
				if ((this._idPastel != value))
				{
					if (this._Pastel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPastelChanging(value);
					this.SendPropertyChanging();
					this._idPastel = value;
					this.SendPropertyChanged("idPastel");
					this.OnidPastelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idIngrediente", DbType="Int NOT NULL")]
		public int idIngrediente
		{
			get
			{
				return this._idIngrediente;
			}
			set
			{
				if ((this._idIngrediente != value))
				{
					if (this._Ingrediente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidIngredienteChanging(value);
					this.SendPropertyChanging();
					this._idIngrediente = value;
					this.SendPropertyChanged("idIngrediente");
					this.OnidIngredienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioIngrediente", DbType="Decimal(8,2) NOT NULL")]
		public decimal precioIngrediente
		{
			get
			{
				return this._precioIngrediente;
			}
			set
			{
				if ((this._precioIngrediente != value))
				{
					this.OnprecioIngredienteChanging(value);
					this.SendPropertyChanging();
					this._precioIngrediente = value;
					this.SendPropertyChanged("precioIngrediente");
					this.OnprecioIngredienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ingrediente_IngredientePastel", Storage="_Ingrediente", ThisKey="idIngrediente", OtherKey="idIngrediente", IsForeignKey=true)]
		public Ingrediente Ingrediente
		{
			get
			{
				return this._Ingrediente.Entity;
			}
			set
			{
				Ingrediente previousValue = this._Ingrediente.Entity;
				if (((previousValue != value) 
							|| (this._Ingrediente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ingrediente.Entity = null;
						previousValue.IngredientePastel.Remove(this);
					}
					this._Ingrediente.Entity = value;
					if ((value != null))
					{
						value.IngredientePastel.Add(this);
						this._idIngrediente = value.idIngrediente;
					}
					else
					{
						this._idIngrediente = default(int);
					}
					this.SendPropertyChanged("Ingrediente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pastel_IngredientePastel", Storage="_Pastel", ThisKey="idPastel", OtherKey="idPastel", IsForeignKey=true)]
		public Pastel Pastel
		{
			get
			{
				return this._Pastel.Entity;
			}
			set
			{
				Pastel previousValue = this._Pastel.Entity;
				if (((previousValue != value) 
							|| (this._Pastel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pastel.Entity = null;
						previousValue.IngredientePastel.Remove(this);
					}
					this._Pastel.Entity = value;
					if ((value != null))
					{
						value.IngredientePastel.Add(this);
						this._idPastel = value.idPastel;
					}
					else
					{
						this._idPastel = default(int);
					}
					this.SendPropertyChanged("Pastel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pastel")]
	public partial class Pastel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPastel;
		
		private string _nombrePastel;
		
		private int _tamanio;
		
		private System.Nullable<bool> _estado;
		
		private EntitySet<IngredientePastel> _IngredientePastel;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPastelChanging(int value);
    partial void OnidPastelChanged();
    partial void OnnombrePastelChanging(string value);
    partial void OnnombrePastelChanged();
    partial void OntamanioChanging(int value);
    partial void OntamanioChanged();
    partial void OnestadoChanging(System.Nullable<bool> value);
    partial void OnestadoChanged();
    #endregion
		
		public Pastel()
		{
			this._IngredientePastel = new EntitySet<IngredientePastel>(new Action<IngredientePastel>(this.attach_IngredientePastel), new Action<IngredientePastel>(this.detach_IngredientePastel));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPastel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPastel
		{
			get
			{
				return this._idPastel;
			}
			set
			{
				if ((this._idPastel != value))
				{
					this.OnidPastelChanging(value);
					this.SendPropertyChanging();
					this._idPastel = value;
					this.SendPropertyChanged("idPastel");
					this.OnidPastelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePastel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombrePastel
		{
			get
			{
				return this._nombrePastel;
			}
			set
			{
				if ((this._nombrePastel != value))
				{
					this.OnnombrePastelChanging(value);
					this.SendPropertyChanging();
					this._nombrePastel = value;
					this.SendPropertyChanged("nombrePastel");
					this.OnnombrePastelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tamanio", DbType="Int NOT NULL")]
		public int tamanio
		{
			get
			{
				return this._tamanio;
			}
			set
			{
				if ((this._tamanio != value))
				{
					this.OntamanioChanging(value);
					this.SendPropertyChanging();
					this._tamanio = value;
					this.SendPropertyChanged("tamanio");
					this.OntamanioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", AutoSync=AutoSync.OnInsert, DbType="Bit", IsDbGenerated=true)]
		public System.Nullable<bool> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pastel_IngredientePastel", Storage="_IngredientePastel", ThisKey="idPastel", OtherKey="idPastel")]
		public EntitySet<IngredientePastel> IngredientePastel
		{
			get
			{
				return this._IngredientePastel;
			}
			set
			{
				this._IngredientePastel.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_IngredientePastel(IngredientePastel entity)
		{
			this.SendPropertyChanging();
			entity.Pastel = this;
		}
		
		private void detach_IngredientePastel(IngredientePastel entity)
		{
			this.SendPropertyChanging();
			entity.Pastel = null;
		}
	}
}
#pragma warning restore 1591
